# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhaoze/workplace/projects/textrank

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhaoze/workplace/projects/textrank

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaoze/workplace/projects/textrank/CMakeFiles /Users/zhaoze/workplace/projects/textrank/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaoze/workplace/projects/textrank/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named segment

# Build rule for target.
segment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 segment
.PHONY : segment

# fast build rule for target.
segment/fast:
	$(MAKE) -f CMakeFiles/segment.dir/build.make CMakeFiles/segment.dir/build
.PHONY : segment/fast

#=============================================================================
# Target rules for targets named keyword
<<<<<<< Updated upstream
=======

# Build rule for target.
keyword: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keyword
.PHONY : keyword

# fast build rule for target.
keyword/fast:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/build
.PHONY : keyword/fast

#=============================================================================
# Target rules for targets named textrank
>>>>>>> Stashed changes

# Build rule for target.
keyword: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keyword
.PHONY : keyword

# fast build rule for target.
keyword/fast:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/build
.PHONY : keyword/fast

#=============================================================================
# Target rules for targets named keysentence

# Build rule for target.
keysentence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keysentence
.PHONY : keysentence

# fast build rule for target.
keysentence/fast:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/build
.PHONY : keysentence/fast

keysentence.o: keysentence.cpp.o

.PHONY : keysentence.o

# target to build an object file
keysentence.cpp.o:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.o
.PHONY : keysentence.cpp.o

keysentence.i: keysentence.cpp.i

.PHONY : keysentence.i

# target to preprocess a source file
keysentence.cpp.i:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.i
.PHONY : keysentence.cpp.i

keysentence.s: keysentence.cpp.s

.PHONY : keysentence.s

# target to generate assembly for a file
keysentence.cpp.s:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.s
.PHONY : keysentence.cpp.s

keyword.o: keyword.cpp.o

.PHONY : keyword.o

# target to build an object file
keyword.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.o
.PHONY : keyword.cpp.o

keyword.i: keyword.cpp.i

.PHONY : keyword.i

# target to preprocess a source file
keyword.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.i
.PHONY : keyword.cpp.i

keyword.s: keyword.cpp.s

.PHONY : keyword.s

# target to generate assembly for a file
keyword.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.s
.PHONY : keyword.cpp.s

KeyWord.o: KeyWord.cpp.o

.PHONY : KeyWord.o

# target to build an object file
KeyWord.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/KeyWord.cpp.o
.PHONY : KeyWord.cpp.o

KeyWord.i: KeyWord.cpp.i

.PHONY : KeyWord.i

# target to preprocess a source file
KeyWord.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/KeyWord.cpp.i
.PHONY : KeyWord.cpp.i

KeyWord.s: KeyWord.cpp.s

.PHONY : KeyWord.s

# target to generate assembly for a file
KeyWord.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/KeyWord.cpp.s
.PHONY : KeyWord.cpp.s

segment.o: segment.cpp.o

.PHONY : segment.o

# target to build an object file
segment.cpp.o:
	$(MAKE) -f CMakeFiles/segment.dir/build.make CMakeFiles/segment.dir/segment.cpp.o
.PHONY : segment.cpp.o

segment.i: segment.cpp.i

.PHONY : segment.i

# target to preprocess a source file
segment.cpp.i:
	$(MAKE) -f CMakeFiles/segment.dir/build.make CMakeFiles/segment.dir/segment.cpp.i
.PHONY : segment.cpp.i

segment.s: segment.cpp.s

.PHONY : segment.s

# target to generate assembly for a file
segment.cpp.s:
	$(MAKE) -f CMakeFiles/segment.dir/build.make CMakeFiles/segment.dir/segment.cpp.s
.PHONY : segment.cpp.s

<<<<<<< Updated upstream
=======
src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/main.cpp.o
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/main.cpp.i
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/main.cpp.s
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

>>>>>>> Stashed changes
src/sentence_rank.o: src/sentence_rank.cpp.o

.PHONY : src/sentence_rank.o

# target to build an object file
src/sentence_rank.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.o
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.o
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/sentence_rank.cpp.o
>>>>>>> Stashed changes
.PHONY : src/sentence_rank.cpp.o

src/sentence_rank.i: src/sentence_rank.cpp.i

.PHONY : src/sentence_rank.i

# target to preprocess a source file
src/sentence_rank.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.i
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.i
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/sentence_rank.cpp.i
>>>>>>> Stashed changes
.PHONY : src/sentence_rank.cpp.i

src/sentence_rank.s: src/sentence_rank.cpp.s

.PHONY : src/sentence_rank.s

# target to generate assembly for a file
src/sentence_rank.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.s
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.s
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/sentence_rank.cpp.s
>>>>>>> Stashed changes
.PHONY : src/sentence_rank.cpp.s

src/text_rank.o: src/text_rank.cpp.o

.PHONY : src/text_rank.o

# target to build an object file
src/text_rank.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.o
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.o
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/text_rank.cpp.o
>>>>>>> Stashed changes
.PHONY : src/text_rank.cpp.o

src/text_rank.i: src/text_rank.cpp.i

.PHONY : src/text_rank.i

# target to preprocess a source file
src/text_rank.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.i
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.i
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/text_rank.cpp.i
>>>>>>> Stashed changes
.PHONY : src/text_rank.cpp.i

src/text_rank.s: src/text_rank.cpp.s

.PHONY : src/text_rank.s

# target to generate assembly for a file
src/text_rank.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.s
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.s
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/text_rank.cpp.s
>>>>>>> Stashed changes
.PHONY : src/text_rank.cpp.s

src/text_utils.o: src/text_utils.cpp.o

.PHONY : src/text_utils.o

# target to build an object file
src/text_utils.cpp.o:
	$(MAKE) -f CMakeFiles/segment.dir/build.make CMakeFiles/segment.dir/src/text_utils.cpp.o
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.o
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.o
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/text_utils.cpp.o
>>>>>>> Stashed changes
.PHONY : src/text_utils.cpp.o

src/text_utils.i: src/text_utils.cpp.i

.PHONY : src/text_utils.i

# target to preprocess a source file
src/text_utils.cpp.i:
	$(MAKE) -f CMakeFiles/segment.dir/build.make CMakeFiles/segment.dir/src/text_utils.cpp.i
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.i
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.i
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/text_utils.cpp.i
>>>>>>> Stashed changes
.PHONY : src/text_utils.cpp.i

src/text_utils.s: src/text_utils.cpp.s

.PHONY : src/text_utils.s

# target to generate assembly for a file
src/text_utils.cpp.s:
	$(MAKE) -f CMakeFiles/segment.dir/build.make CMakeFiles/segment.dir/src/text_utils.cpp.s
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.s
<<<<<<< Updated upstream
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.s
=======
	$(MAKE) -f CMakeFiles/textrank.dir/build.make CMakeFiles/textrank.dir/src/text_utils.cpp.s
>>>>>>> Stashed changes
.PHONY : src/text_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... segment"
	@echo "... keyword"
<<<<<<< Updated upstream
	@echo "... keysentence"
	@echo "... keysentence.o"
	@echo "... keysentence.i"
	@echo "... keysentence.s"
	@echo "... keyword.o"
	@echo "... keyword.i"
	@echo "... keyword.s"
=======
	@echo "... textrank"
	@echo "... KeyWord.o"
	@echo "... KeyWord.i"
	@echo "... KeyWord.s"
>>>>>>> Stashed changes
	@echo "... segment.o"
	@echo "... segment.i"
	@echo "... segment.s"
	@echo "... src/sentence_rank.o"
	@echo "... src/sentence_rank.i"
	@echo "... src/sentence_rank.s"
	@echo "... src/text_rank.o"
	@echo "... src/text_rank.i"
	@echo "... src/text_rank.s"
	@echo "... src/text_utils.o"
	@echo "... src/text_utils.i"
	@echo "... src/text_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

