# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhaoze/workplace/projects/textSummary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhaoze/workplace/projects/textSummary

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaoze/workplace/projects/textSummary/CMakeFiles /Users/zhaoze/workplace/projects/textSummary/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaoze/workplace/projects/textSummary/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named keyword

# Build rule for target.
keyword: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keyword
.PHONY : keyword

# fast build rule for target.
keyword/fast:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/build
.PHONY : keyword/fast

#=============================================================================
# Target rules for targets named text

# Build rule for target.
text: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 text
.PHONY : text

# fast build rule for target.
text/fast:
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/build
.PHONY : text/fast

#=============================================================================
# Target rules for targets named keysentence

# Build rule for target.
keysentence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keysentence
.PHONY : keysentence

# fast build rule for target.
keysentence/fast:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/build
.PHONY : keysentence/fast

keysentence.o: keysentence.cpp.o

.PHONY : keysentence.o

# target to build an object file
keysentence.cpp.o:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.o
.PHONY : keysentence.cpp.o

keysentence.i: keysentence.cpp.i

.PHONY : keysentence.i

# target to preprocess a source file
keysentence.cpp.i:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.i
.PHONY : keysentence.cpp.i

keysentence.s: keysentence.cpp.s

.PHONY : keysentence.s

# target to generate assembly for a file
keysentence.cpp.s:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.s
.PHONY : keysentence.cpp.s

keyword.o: keyword.cpp.o

.PHONY : keyword.o

# target to build an object file
keyword.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.o
.PHONY : keyword.cpp.o

keyword.i: keyword.cpp.i

.PHONY : keyword.i

# target to preprocess a source file
keyword.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.i
.PHONY : keyword.cpp.i

keyword.s: keyword.cpp.s

.PHONY : keyword.s

# target to generate assembly for a file
keyword.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.s
.PHONY : keyword.cpp.s

src/sentence_rank.o: src/sentence_rank.cpp.o

.PHONY : src/sentence_rank.o

# target to build an object file
src/sentence_rank.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.o
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/sentence_rank.cpp.o
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.o
.PHONY : src/sentence_rank.cpp.o

src/sentence_rank.i: src/sentence_rank.cpp.i

.PHONY : src/sentence_rank.i

# target to preprocess a source file
src/sentence_rank.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.i
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/sentence_rank.cpp.i
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.i
.PHONY : src/sentence_rank.cpp.i

src/sentence_rank.s: src/sentence_rank.cpp.s

.PHONY : src/sentence_rank.s

# target to generate assembly for a file
src/sentence_rank.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.s
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/sentence_rank.cpp.s
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.s
.PHONY : src/sentence_rank.cpp.s

src/text_rank.o: src/text_rank.cpp.o

.PHONY : src/text_rank.o

# target to build an object file
src/text_rank.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.o
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/text_rank.cpp.o
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.o
.PHONY : src/text_rank.cpp.o

src/text_rank.i: src/text_rank.cpp.i

.PHONY : src/text_rank.i

# target to preprocess a source file
src/text_rank.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.i
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/text_rank.cpp.i
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.i
.PHONY : src/text_rank.cpp.i

src/text_rank.s: src/text_rank.cpp.s

.PHONY : src/text_rank.s

# target to generate assembly for a file
src/text_rank.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.s
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/text_rank.cpp.s
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.s
.PHONY : src/text_rank.cpp.s

src/text_utils.o: src/text_utils.cpp.o

.PHONY : src/text_utils.o

# target to build an object file
src/text_utils.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.o
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/text_utils.cpp.o
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.o
.PHONY : src/text_utils.cpp.o

src/text_utils.i: src/text_utils.cpp.i

.PHONY : src/text_utils.i

# target to preprocess a source file
src/text_utils.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.i
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/text_utils.cpp.i
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.i
.PHONY : src/text_utils.cpp.i

src/text_utils.s: src/text_utils.cpp.s

.PHONY : src/text_utils.s

# target to generate assembly for a file
src/text_utils.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.s
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/src/text_utils.cpp.s
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.s
.PHONY : src/text_utils.cpp.s

summary.o: summary.cpp.o

.PHONY : summary.o

# target to build an object file
summary.cpp.o:
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/summary.cpp.o
.PHONY : summary.cpp.o

summary.i: summary.cpp.i

.PHONY : summary.i

# target to preprocess a source file
summary.cpp.i:
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/summary.cpp.i
.PHONY : summary.cpp.i

summary.s: summary.cpp.s

.PHONY : summary.s

# target to generate assembly for a file
summary.cpp.s:
	$(MAKE) -f CMakeFiles/text.dir/build.make CMakeFiles/text.dir/summary.cpp.s
.PHONY : summary.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... keyword"
	@echo "... text"
	@echo "... keysentence"
	@echo "... keysentence.o"
	@echo "... keysentence.i"
	@echo "... keysentence.s"
	@echo "... keyword.o"
	@echo "... keyword.i"
	@echo "... keyword.s"
	@echo "... src/sentence_rank.o"
	@echo "... src/sentence_rank.i"
	@echo "... src/sentence_rank.s"
	@echo "... src/text_rank.o"
	@echo "... src/text_rank.i"
	@echo "... src/text_rank.s"
	@echo "... src/text_utils.o"
	@echo "... src/text_utils.i"
	@echo "... src/text_utils.s"
	@echo "... summary.o"
	@echo "... summary.i"
	@echo "... summary.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

