# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhaoze/workplace/projects/textSummary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhaoze/workplace/projects/textSummary

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaoze/workplace/projects/textSummary/CMakeFiles /Users/zhaoze/workplace/projects/textSummary/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhaoze/workplace/projects/textSummary/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named keysentence

# Build rule for target.
keysentence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keysentence
.PHONY : keysentence

# fast build rule for target.
keysentence/fast:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/build
.PHONY : keysentence/fast

#=============================================================================
# Target rules for targets named keyword

# Build rule for target.
keyword: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keyword
.PHONY : keyword

# fast build rule for target.
keyword/fast:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/build
.PHONY : keyword/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named fromtextTopN

# Build rule for target.
fromtextTopN: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fromtextTopN
.PHONY : fromtextTopN

# fast build rule for target.
fromtextTopN/fast:
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/build
.PHONY : fromtextTopN/fast

#=============================================================================
# Target rules for targets named fromtext

# Build rule for target.
fromtext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fromtext
.PHONY : fromtext

# fast build rule for target.
fromtext/fast:
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/build
.PHONY : fromtext/fast

keysentence.o: keysentence.cpp.o

.PHONY : keysentence.o

# target to build an object file
keysentence.cpp.o:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.o
.PHONY : keysentence.cpp.o

keysentence.i: keysentence.cpp.i

.PHONY : keysentence.i

# target to preprocess a source file
keysentence.cpp.i:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.i
.PHONY : keysentence.cpp.i

keysentence.s: keysentence.cpp.s

.PHONY : keysentence.s

# target to generate assembly for a file
keysentence.cpp.s:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/keysentence.cpp.s
.PHONY : keysentence.cpp.s

keyword.o: keyword.cpp.o

.PHONY : keyword.o

# target to build an object file
keyword.cpp.o:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.o
.PHONY : keyword.cpp.o

keyword.i: keyword.cpp.i

.PHONY : keyword.i

# target to preprocess a source file
keyword.cpp.i:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.i
.PHONY : keyword.cpp.i

keyword.s: keyword.cpp.s

.PHONY : keyword.s

# target to generate assembly for a file
keyword.cpp.s:
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/keyword.cpp.s
.PHONY : keyword.cpp.s

src/sentence_rank.o: src/sentence_rank.cpp.o

.PHONY : src/sentence_rank.o

# target to build an object file
src/sentence_rank.cpp.o:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.o
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/sentence_rank.cpp.o
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/sentence_rank.cpp.o
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/sentence_rank.cpp.o
.PHONY : src/sentence_rank.cpp.o

src/sentence_rank.i: src/sentence_rank.cpp.i

.PHONY : src/sentence_rank.i

# target to preprocess a source file
src/sentence_rank.cpp.i:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.i
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/sentence_rank.cpp.i
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/sentence_rank.cpp.i
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/sentence_rank.cpp.i
.PHONY : src/sentence_rank.cpp.i

src/sentence_rank.s: src/sentence_rank.cpp.s

.PHONY : src/sentence_rank.s

# target to generate assembly for a file
src/sentence_rank.cpp.s:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/sentence_rank.cpp.s
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/sentence_rank.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/sentence_rank.cpp.s
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/sentence_rank.cpp.s
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/sentence_rank.cpp.s
.PHONY : src/sentence_rank.cpp.s

src/text_rank.o: src/text_rank.cpp.o

.PHONY : src/text_rank.o

# target to build an object file
src/text_rank.cpp.o:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.o
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/text_rank.cpp.o
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/text_rank.cpp.o
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/text_rank.cpp.o
.PHONY : src/text_rank.cpp.o

src/text_rank.i: src/text_rank.cpp.i

.PHONY : src/text_rank.i

# target to preprocess a source file
src/text_rank.cpp.i:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.i
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/text_rank.cpp.i
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/text_rank.cpp.i
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/text_rank.cpp.i
.PHONY : src/text_rank.cpp.i

src/text_rank.s: src/text_rank.cpp.s

.PHONY : src/text_rank.s

# target to generate assembly for a file
src/text_rank.cpp.s:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_rank.cpp.s
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_rank.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/text_rank.cpp.s
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/text_rank.cpp.s
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/text_rank.cpp.s
.PHONY : src/text_rank.cpp.s

src/text_utils.o: src/text_utils.cpp.o

.PHONY : src/text_utils.o

# target to build an object file
src/text_utils.cpp.o:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.o
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/text_utils.cpp.o
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/text_utils.cpp.o
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/text_utils.cpp.o
.PHONY : src/text_utils.cpp.o

src/text_utils.i: src/text_utils.cpp.i

.PHONY : src/text_utils.i

# target to preprocess a source file
src/text_utils.cpp.i:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.i
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/text_utils.cpp.i
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/text_utils.cpp.i
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/text_utils.cpp.i
.PHONY : src/text_utils.cpp.i

src/text_utils.s: src/text_utils.cpp.s

.PHONY : src/text_utils.s

# target to generate assembly for a file
src/text_utils.cpp.s:
	$(MAKE) -f CMakeFiles/keysentence.dir/build.make CMakeFiles/keysentence.dir/src/text_utils.cpp.s
	$(MAKE) -f CMakeFiles/keyword.dir/build.make CMakeFiles/keyword.dir/src/text_utils.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/text_utils.cpp.s
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/src/text_utils.cpp.s
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/src/text_utils.cpp.s
.PHONY : src/text_utils.cpp.s

summary_fromtext.o: summary_fromtext.cpp.o

.PHONY : summary_fromtext.o

# target to build an object file
summary_fromtext.cpp.o:
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/summary_fromtext.cpp.o
.PHONY : summary_fromtext.cpp.o

summary_fromtext.i: summary_fromtext.cpp.i

.PHONY : summary_fromtext.i

# target to preprocess a source file
summary_fromtext.cpp.i:
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/summary_fromtext.cpp.i
.PHONY : summary_fromtext.cpp.i

summary_fromtext.s: summary_fromtext.cpp.s

.PHONY : summary_fromtext.s

# target to generate assembly for a file
summary_fromtext.cpp.s:
	$(MAKE) -f CMakeFiles/fromtext.dir/build.make CMakeFiles/fromtext.dir/summary_fromtext.cpp.s
.PHONY : summary_fromtext.cpp.s

summary_fromtext_topN.o: summary_fromtext_topN.cpp.o

.PHONY : summary_fromtext_topN.o

# target to build an object file
summary_fromtext_topN.cpp.o:
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/summary_fromtext_topN.cpp.o
.PHONY : summary_fromtext_topN.cpp.o

summary_fromtext_topN.i: summary_fromtext_topN.cpp.i

.PHONY : summary_fromtext_topN.i

# target to preprocess a source file
summary_fromtext_topN.cpp.i:
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/summary_fromtext_topN.cpp.i
.PHONY : summary_fromtext_topN.cpp.i

summary_fromtext_topN.s: summary_fromtext_topN.cpp.s

.PHONY : summary_fromtext_topN.s

# target to generate assembly for a file
summary_fromtext_topN.cpp.s:
	$(MAKE) -f CMakeFiles/fromtextTopN.dir/build.make CMakeFiles/fromtextTopN.dir/summary_fromtext_topN.cpp.s
.PHONY : summary_fromtext_topN.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... keysentence"
	@echo "... keyword"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... fromtextTopN"
	@echo "... fromtext"
	@echo "... keysentence.o"
	@echo "... keysentence.i"
	@echo "... keysentence.s"
	@echo "... keyword.o"
	@echo "... keyword.i"
	@echo "... keyword.s"
	@echo "... src/sentence_rank.o"
	@echo "... src/sentence_rank.i"
	@echo "... src/sentence_rank.s"
	@echo "... src/text_rank.o"
	@echo "... src/text_rank.i"
	@echo "... src/text_rank.s"
	@echo "... src/text_utils.o"
	@echo "... src/text_utils.i"
	@echo "... src/text_utils.s"
	@echo "... summary_fromtext.o"
	@echo "... summary_fromtext.i"
	@echo "... summary_fromtext.s"
	@echo "... summary_fromtext_topN.o"
	@echo "... summary_fromtext_topN.i"
	@echo "... summary_fromtext_topN.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

